# Generated by Django 5.1.7 on 2025-03-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatus_unidad',
            options={'permissions': [('can_view_estatus_unidad', 'Estatus de Unidades'), ('can_add_estatus_unidad', 'Estatus de Unidades - Agregar'), ('can_edit_estatus_unidad', 'Estatus de Unidades - Modificar'), ('can_delete_estatus_unidad', 'Estatus de Unidades - Eliminar')], 'verbose_name_plural': 'Estatus de unidades'},
        ),
        migrations.AlterModelOptions(
            name='lineas_unidades',
            options={'permissions': [('can_view_lineas_unidad', 'Lineas'), ('can_add_lineas_unidad', 'Lineas - Agregar'), ('can_edit_lineas_unidad', 'Lineas - Modificar'), ('can_delete_lineas_unidad', 'Lineas - Eliminar')], 'verbose_name_plural': 'Lineas'},
        ),
    ]
