# Generated by Django 5.1.7 on 2025-03-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_estatus_unidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatus_unidad',
            options={'permissions': [('can_view_estatus_unidad', 'Estatus de Unidades'), ('can_add_estatus_unidad', 'Agregar'), ('can_edit_estatus_unidad', 'Modificar'), ('can_delete_estatus_unidad', 'Eliminar')], 'verbose_name_plural': 'Estatus de unidades'},
        ),
        migrations.AlterModelOptions(
            name='lineas_unidades',
            options={'permissions': [('can_view_lineas_unidad', 'Lineas'), ('can_add_lineas_unidad', 'Agregar'), ('can_edit_lineas_unidad', 'Modificar'), ('can_delete_lineas_unidad', 'Eliminar')], 'verbose_name_plural': 'Lineas'},
        ),
    ]
