# Generated by Django 5.1.7 on 2025-03-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id_proceso', models.CharField(db_column='id_proceso', max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nombre_proceso', models.CharField(max_length=250)),
                ('descripcion_proceso', models.CharField(max_length=250, verbose_name='Nombre')),
                ('tipo_proceso', models.CharField(choices=[('catalogo', 'Catalogo'), ('procesos', 'Proceso'), ('reportes', 'Reportes'), ('configuracion', 'Configuracion')], max_length=100, verbose_name='Tipo de Proceso')),
                ('id_proceso_padre', models.ForeignKey(blank=True, db_column='id_proceso_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso', to='main.procesos', verbose_name='Proceso Principal')),
            ],
            options={
                'verbose_name_plural': 'Procesos',
            },
        ),
    ]
